---

name: Dockerized Nodejs Service Deployment with Docker Hub

on:
  push:
    branches:
      - 'main'

  workflow_dispatch:

jobs:
  prepare_image:
    runs-on: ubuntu-24.04

    steps:

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          registry: docker.io # Don't need this line because Docker is default value for this action
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          push: true
          tags: docker.io/${{ vars.DOCKERHUB_USERNAME }}/dockerized-nodejs-service:${{ github.sha }}
  deploy:
      runs-on: ubuntu-24.04

      steps:

        - name: Pull Nodejs Application Image Built
          uses: appleboy/ssh-action@v1
          env:
            DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
            DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          with:
            host: ${{ vars.SERVER_IP }}
            username: ${{ vars.SERVER_USER }}
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            envs: DOCKERHUB_USERNAME, DOCKERHUB_TOKEN
            script: |
              echo "$DOCKERHUB_TOKEN" | sudo docker login -u "$DOCKERHUB_USERNAME" --password-stdin
              sudo docker pull "$DOCKERHUB_USERNAME"/dockerized-nodejs-service:${{ github.sha }}
        
        - name: Run Nodejs Container on the VM
          uses: appleboy/ssh-action@v1
          env:
            APP_USERNAME: ${{ secrets.APP_USERNAME }}
            APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
            SECRET_MESSAGE: ${{ secrets.SECRET_MESSAGE }}
            DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
          with:
            host: ${{ vars.SERVER_IP }}
            username: ${{ vars.SERVER_USER }}
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            envs: APP_USERNAME, APP_PASSWORD, SECRET_MESSAGE, DOCKERHUB_USERNAME
            script: |
              sudo docker run --name dockerized-nodejs-service -e APP_USERNAME="$APP_USERNAME" \
              -e APP_PASSWORD="$APP_PASSWORD" -e SECRET_MESSAGE="$SECRET_MESSAGE" \
              -p 3000:3000 "$DOCKERHUB_USERNAME"/dockerized-nodejs-service:${{ github.sha }}
